# Generated by Django 6.1.1 on 2026-09-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='conteudo',
            field=models.CharField(default=0, max_length=280),
            preserve_default=False,
        ),
    ]
